[sample_connection]
engine = "postgresql"
environment = "production"
host = "localhost"
port = 5432
database = "dbaghu"
username = "postgres"
password = "${SAMPLE_CONNECTION_PASSWORD}"
sslmode = "disable"
